# Generated by Django 3.1.5 on 2021-01-17 02:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('realm', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('session_id', models.UUIDField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('connected', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verto.channel')),
            ],
        ),
    ]
