# Generated by Django 3.2.2 on 2021-05-15 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sofia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('sofiaprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sofia.sofiaprofile')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('proxy', models.CharField(max_length=50)),
                ('realm', models.CharField(max_length=50)),
            ],
            bases=('sofia.sofiaprofile',),
        ),
        migrations.CreateModel(
            name='DidNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=50)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
            ],
        ),
        migrations.CreateModel(
            name='AclAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
            ],
            options={
                'verbose_name': 'ACL address',
                'verbose_name_plural': 'ACL addresses',
            },
        ),
        migrations.AddConstraint(
            model_name='didnumber',
            constraint=models.UniqueConstraint(fields=('number', 'gateway'), name='gateway_didnumber_is_unique'),
        ),
    ]
