# Generated by Django 3.2.2 on 2021-05-17 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0001_initial'),
        ('intercom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundtransfer',
            name='extension',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom.extension'),
        ),
        migrations.AddField(
            model_name='didnumber',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway'),
        ),
        migrations.AddField(
            model_name='acladdress',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway'),
        ),
        migrations.AddConstraint(
            model_name='didnumber',
            constraint=models.UniqueConstraint(fields=('phone_number', 'gateway'), name='gateway_didnumber_is_unique'),
        ),
    ]
