# Generated by Django 3.2.2 on 2021-05-15 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sofia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercom',
            fields=[
                ('sofiaprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sofia.sofiaprofile')),
            ],
            bases=('sofia.sofiaprofile',),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('username', models.SlugField()),
                ('password', models.CharField(max_length=50)),
                ('registered', models.DateTimeField(blank=True, null=True)),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
            ],
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('username', 'intercom'), name='per_intercom_unique_username'),
        ),
    ]
