# Generated by Django 3.2 on 2021-04-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='verto.channel')),
            ],
        ),
    ]
