# Generated by Django 3.2.2 on 2021-05-11 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SofiaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(unique=True)),
                ('domain', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayProfile',
            fields=[
                ('sofiaprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sofia.sofiaprofile')),
            ],
            bases=('sofia.sofiaprofile',),
        ),
        migrations.CreateModel(
            name='IntercomProfile',
            fields=[
                ('sofiaprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sofia.sofiaprofile')),
            ],
            bases=('sofia.sofiaprofile',),
        ),
        migrations.CreateModel(
            name='SipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=15)),
                ('username', models.SlugField()),
                ('password', models.CharField(max_length=50)),
                ('registered', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sofia.gatewayprofile')),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofia.intercomprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SlugField()),
                ('intercom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sofia.intercomprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DidNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sofia.gatewayprofile')),
            ],
            options={
                'verbose_name': 'DID number',
            },
        ),
        migrations.AddConstraint(
            model_name='sipline',
            constraint=models.UniqueConstraint(fields=('username', 'intercom'), name='unique_username'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('number', 'intercom'), name='unique_extension_number'),
        ),
    ]
