# Generated by Django 3.2.2 on 2021-05-15 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extension', '0001_initial'),
        ('intercom', '0001_initial'),
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMatchCall',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.action')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
                ('pattern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extension.matchextension')),
            ],
            bases=('extension.action',),
        ),
        migrations.CreateModel(
            name='OutboundCall',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.action')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extension.extension')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
            ],
            bases=('extension.action',),
        ),
        migrations.CreateModel(
            name='LineCall',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.action')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extension.extension')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom.line')),
            ],
            bases=('extension.action',),
        ),
        migrations.CreateModel(
            name='InboundTransfer',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.action')),
                ('did_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gateway.didnumber')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension.extension')),
            ],
            bases=('extension.action',),
        ),
        migrations.CreateModel(
            name='GroupCall',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.action')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extension.extension')),
                ('lines', models.ManyToManyField(to='intercom.Line')),
            ],
            bases=('extension.action',),
        ),
        migrations.AddConstraint(
            model_name='outboundmatchcall',
            constraint=models.UniqueConstraint(fields=('pattern', 'gateway'), name='call_outboundmatchcall_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='outboundcall',
            constraint=models.UniqueConstraint(fields=('extension', 'gateway'), name='call_outboundcall_is_unique'),
        ),
    ]
