# Generated by Django 3.2.2 on 2021-05-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sofia', '0001_initial'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action.action')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sofia.sipline')),
            ],
            bases=('action.action',),
        ),
    ]
