# Generated by Django 3.2.2 on 2021-05-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialplan', '0001_initial'),
        ('gateway', '0001_initial'),
        ('intercom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundCall',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialplan.action')),
                ('number', models.CharField(blank=True, max_length=50)),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom.extension')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
            ],
            bases=('dialplan.action',),
        ),
        migrations.CreateModel(
            name='LineCall',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialplan.action')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom.extension')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom.line')),
            ],
            bases=('dialplan.action',),
        ),
        migrations.CreateModel(
            name='InboundTransfer',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialplan.action')),
                ('did_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gateway.didnumber')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.extension')),
            ],
            bases=('dialplan.action',),
        ),
        migrations.CreateModel(
            name='GroupCall',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialplan.action')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom.extension')),
                ('lines', models.ManyToManyField(to='intercom.Line')),
            ],
            bases=('dialplan.action',),
        ),
    ]
