# Generated by Django 3.0.8 on 2020-07-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='Snork', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
