# Generated by Django 3.0.8 on 2020-07-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20200728_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='name',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='public',
        ),
        migrations.AddField(
            model_name='channel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_operator',
            field=models.BooleanField(default=False),
        ),
    ]
