# Generated by Django 3.1 on 2020-09-06 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20200905_0023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Client',
        ),
    ]
