# Generated by Django 3.2.2 on 2021-05-15 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intercom', '0001_initial'),
        ('verto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('pattern', models.CharField(max_length=50)),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('extension', models.CharField(max_length=50)),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('publish', models.BooleanField(default=True)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='verto.channel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='matchextension',
            constraint=models.UniqueConstraint(fields=('pattern', 'intercom'), name='extension_matchextension_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('extension', 'intercom'), name='extension_extension_is_unique'),
        ),
    ]
