# Generated by Django 3.2.2 on 2021-05-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intercom', '0001_initial'),
        ('gateway', '0001_initial'),
        ('verto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('publish', models.BooleanField(default=True)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='verto.channel')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCall',
            fields=[
                ('extension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.extension')),
            ],
            bases=('extension.extension',),
        ),
        migrations.CreateModel(
            name='InboundTransfer',
            fields=[
                ('extension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.extension')),
            ],
            bases=('extension.extension',),
        ),
        migrations.CreateModel(
            name='IntercomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=50)),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
            ],
        ),
        migrations.CreateModel(
            name='IntercomMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('pattern', models.CharField(max_length=50)),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundMatchCall',
            fields=[
                ('extension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.extension')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
                ('pattern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extension.intercommatch')),
            ],
            bases=('extension.extension',),
        ),
        migrations.CreateModel(
            name='OutboundCall',
            fields=[
                ('extension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.extension')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
                ('number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extension.intercomnumber')),
            ],
            bases=('extension.extension',),
        ),
        migrations.CreateModel(
            name='LineCall',
            fields=[
                ('extension_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extension.extension')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom.line')),
                ('number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extension.intercomnumber')),
            ],
            bases=('extension.extension',),
        ),
        migrations.AddConstraint(
            model_name='intercomnumber',
            constraint=models.UniqueConstraint(fields=('number', 'intercom'), name='extension_intercomnumber_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='intercommatch',
            constraint=models.UniqueConstraint(fields=('pattern', 'intercom'), name='extension_intercommatch_is_unique'),
        ),
        migrations.AddField(
            model_name='inboundtransfer',
            name='number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gateway.didnumber'),
        ),
        migrations.AddField(
            model_name='inboundtransfer',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension.intercomnumber'),
        ),
        migrations.AddField(
            model_name='groupcall',
            name='lines',
            field=models.ManyToManyField(to='intercom.Line'),
        ),
        migrations.AddField(
            model_name='groupcall',
            name='number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extension.intercomnumber'),
        ),
        migrations.AddConstraint(
            model_name='outboundmatchcall',
            constraint=models.UniqueConstraint(fields=('pattern', 'gateway'), name='extension_outboundmatchcall_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='outboundcall',
            constraint=models.UniqueConstraint(fields=('number', 'gateway'), name='extension_outboundcall_is_unique'),
        ),
    ]
