# Generated by Django 3.2.2 on 2021-05-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0001_initial'),
        ('verto', '0001_initial'),
        ('sofia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('extension_number', models.CharField(max_length=50)),
                ('pcre_match', models.BooleanField(default=False)),
                ('web_enabled', models.BooleanField(default=False)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='verto.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Intercom',
            fields=[
                ('sofiaprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sofia.sofiaprofile')),
            ],
            bases=('sofia.sofiaprofile',),
        ),
        migrations.CreateModel(
            name='IntercomAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom.extension')),
            ],
        ),
        migrations.CreateModel(
            name='CallGroup',
            fields=[
                ('intercomaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intercom.intercomaction')),
            ],
            bases=('intercom.intercomaction',),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('username', models.SlugField()),
                ('password', models.CharField(max_length=50)),
                ('registered', models.DateTimeField(blank=True, null=True)),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
            ],
        ),
        migrations.AddField(
            model_name='extension',
            name='intercom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom'),
        ),
        migrations.CreateModel(
            name='OutboundCall',
            fields=[
                ('intercomaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intercom.intercomaction')),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('caller_id_name', models.CharField(max_length=15)),
                ('caller_id_number', models.CharField(max_length=50)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
            ],
            bases=('intercom.intercomaction',),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('username', 'intercom'), name='per_intercom_unique_username'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('extension_number', 'intercom'), name='intercom_extension_is_unique'),
        ),
        migrations.AddField(
            model_name='callgroup',
            name='lines',
            field=models.ManyToManyField(to='intercom.Line'),
        ),
    ]
