# Generated by Django 3.2.2 on 2021-05-18 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intercom', '0001_initial'),
        ('gateway', '0001_initial'),
        ('verto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('extension_number', models.CharField(max_length=50)),
                ('web_enabled', models.BooleanField(default=False)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='verto.channel')),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
            ],
        ),
        migrations.CreateModel(
            name='IntercomAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom_dialplan.extension')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCallExtension',
            fields=[
                ('intercomaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intercom_dialplan.intercomaction')),
            ],
            bases=('intercom_dialplan.intercomaction',),
        ),
        migrations.CreateModel(
            name='OutboundCallExtension',
            fields=[
                ('intercomaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intercom_dialplan.intercomaction')),
                ('cid_name', models.CharField(max_length=50)),
                ('cid_number', models.CharField(max_length=50)),
                ('outbound_number', models.CharField(blank=True, max_length=50)),
            ],
            bases=('intercom_dialplan.intercomaction',),
        ),
        migrations.CreateModel(
            name='OutboundCallMatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expression', models.CharField(max_length=50)),
                ('cid_name', models.CharField(blank=True, max_length=50)),
                ('cid_number', models.CharField(max_length=50)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
            ],
        ),
        migrations.CreateModel(
            name='InboundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gateway.didnumber')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom_dialplan.extension')),
            ],
        ),
        migrations.AddConstraint(
            model_name='outboundcallmatcher',
            constraint=models.UniqueConstraint(fields=('expression', 'intercom'), name='intercom_dialplan_outboundcallmatcher_is_unique'),
        ),
        migrations.AddField(
            model_name='outboundcallextension',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway'),
        ),
        migrations.AddField(
            model_name='groupcallextension',
            name='lines',
            field=models.ManyToManyField(to='intercom.Line'),
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('extension_number', 'intercom'), name='intercom_dialplan_extension_is_unique'),
        ),
    ]
